[package]
name = "rtwins"
version = "0.1.0"
authors = ["Mariusz Midor <mmidor@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.5.4"
unicode-width = "0.1"
# enum-iterator = "0.7.0"
termios = "0.3"
# nix = "0.23"
libc = "0.2"

[profile.release]
# https://jamesmunns.com/blog/tinyrocket/
opt-level = 'z'  # Optimize for size.
lto = true
codegen-units = 1
#panic = 'abort'

[profile.dev]
debug = true
lto = false
codegen-units = 2

[features]
fast_line = []
