[package]
name = "rtwins"
version = "0.1.0"
authors = ["Mariusz Midor <mmidor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

