[package]
name = "rtwins"
version = "0.2.0"
authors = ["Mariusz Midor <mmidor@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.5.4"
unicode-width = "0.1"
# enum-iterator = "0.7.0"
libc = "0.2"
chrono = "0.4"
lazy_static = "1"

[profile.release]
# https://jamesmunns.com/blog/tinyrocket/
opt-level = 'z'  # Optimize for size.
lto = true
codegen-units = 1
#panic = 'abort'

[profile.dev]
debug = true
lto = false
codegen-units = 2

[features]
# enable fast line drawing on terminals supporting code ESC-b
fast_line = []
