[package]
name = "rtwins"
version = "0.1.0"
authors = ["Mariusz Midor <mmidor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
# https://jamesmunns.com/blog/tinyrocket/
opt-level = 'z'  # Optimize for size.
lto = true
codegen-units = 1
# panic = 'abort'
