[package]
name = "rtwins"
version = "0.1.0"
authors = ["Mariusz Midor <mmidor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# enum-iterator = "0.7.0"
num_enum = "0.5.4"
unicode-width = "0.1"

[profile.release]
# https://jamesmunns.com/blog/tinyrocket/
opt-level = 'z'  # Optimize for size.
lto = true
codegen-units = 1
# panic = 'abort'
